<?php

/**
 * @file
 * Contains hooks implemeted.
 */

use Drupal\Component\Utility\SafeMarkup;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_entity_insert().
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function cron_queue_email_entity_insert(EntityInterface $entity) {

  if ($entity->getEntityTypeId() !== 'user') {
    return;
  }
  /** @var QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  /** @var QueueInterface $queue */

  //$queue = $queue_factory->get('cron_user_email');
    $queue = $queue_factory->get('manual_user_email');
  $item = new \stdClass();
  $item->uid = $entity->id();
  $queue->createItem($item);
}

/**
 * Implements hook_mail().
 */
function cron_queue_email_mail($key, &$message, $params) {
  switch ($key) {
    case 'register_user_send_email':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Welcome new user.');
      $message['body'][] = SafeMarkup::checkPlain($params['message']);
      break;
  }
}